### ISSUE TITLE
J_unacc can not be recognized

### ISSUE THREAD

**Issue by AA1HSHH** [No-12136/CTCA#1]
Hi, I tried inputting the values (10, 2, 1, 10, [0.1, 0.2], 0) into the Sto_CTCA function from a repository, but I encountered an error. I suspect that the code in the repository might not be complete. Could you please help me check this?
Errors I got are as follows。

Sto_CTCA(10,2,1,10,[0.1,0.2],0)
函数或变量 'J_unacc' 无法识别。

出错 V_Travel>UPD_v (line 76)
        V_info_Cur(k).V(J_unacc)=d(J_unacc)/delta_T;

出错 V_Travel (line 12)
[Ve_Change,Ctrl_para]=UPD_v(Pre_para,Ctrl_para,Traffic_para);

出错 Sto_CTCA (line 114)
    Ctrl_para=V_Travel(Pre_para,Traffic_para,Ctrl_para);

**Comment by DiMY-CN** [comment]
Thanks for your feedback, the file did have some code missing and some incorrect comments present, I have re-released the revised version.
Also, I noticed that you tried to use a road with a length of 10m, but the algorithm's default speed limit is already 25m/s, and at the default 1s update interval, there will be a noticeable jump in the dynamic traffic evolution graph.
